[package]
name = "ingest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.59"
fs2 = "0.4.3"
thiserror = "1.0.32"
walkdir = "2.3.2"
